### ISSUE TITLE
HDRP Motion Vectors not working

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyImpostors-Feedback#10]

**Comment by Dawie3565** [comment]
**this item is now tracking in**
https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/172

**Comment by Dawie3565** [comment]
Closed in Amplify Impostors v0.9.8.4
v0.9.8.4 testing in HDRP 15x with custom runtime shaders set Motion Vectors and precomputed Motion also, no artifacts or issues found. 

if any new issues please ask for re-report as new issue with more detail including unity version numbers / API and how to replicate.
