### ISSUE TITLE
Template Design

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyImpostors-Feedback#11]
1. The template always adds _Albedo and _Normals even if not used. We should be able to have and handle our own bakes as we want via the custom texture samplers, and the impostor should only take care of sampling the textures and blend them.

![image](https://user-images.githubusercontent.com/33637574/203131795-94c29281-975b-49b9-98cd-2d98141012b7.png)
![image](https://user-images.githubusercontent.com/33637574/203131830-ba708a88-922f-4e12-87be-9572d285dfca.png)

2. An impostor could work with any template because we just provide some interpolated textures and vertex output via the Impostor Node. This way we can have unlit shaders, simple lit, custom lit, etc, without needing to duplicate the templates.

3. The impostor is always performing a clip, in fact, it does 2 clips. This could be done at the end, in case the user wants to add something to that clip. In my case, the shader is performing 3 clips.

![image](https://user-images.githubusercontent.com/33637574/203133007-9257dca2-08ec-4f68-8938-b1d742cfd0bc.png)

4. The ImpostorFragment could take care of a single texture at a time, instead of doing the entire SurfaceOutput maybe?

5. URP/HDRP bakers are not needed, the BIRP one works for all.

6. The built in shaders could be moved to templates to have only 1 system for everything.  I can help to make the bakers work with the unity shaders. Fewer shaders to maintain, which are all written in a different style. If the custom templates are dropped, the amplify templates can be used, so the impostor only needs the bakers. Win win win

How I would redesign the shaders, the impostor node adds interpolators, the vertex/frag calculation, and outputs the textures with parallax and that's it. Any template can be used after and we just hook the textures, perform the alpha clip, etc

**Comment by Dawie3565** [comment]
**this item is now tracking in**
https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/171
