### ISSUE TITLE
Having Amplify impostors pack will reimport everything

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyImpostors-Feedback#12]
Having Amplify impostors pack will reimport everything if a new package is imported.

**Comment by BOXOPHOBIC** [comment]
https://www.youtube.com/watch?v=xKMFnj1nhkg
after this is compiled, the texture importing starts
![image](https://user-images.githubusercontent.com/33637574/210875229-a93b0fef-dc77-42f4-87cc-0f5799e12861.png)

**Comment by Dawie3565** [comment]
**this item is now tracking in**
https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/168
