### ISSUE TITLE
Depth Precision issue with Quest 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyImpostors-Feedback#21]
Diogo item7

Issue
Reported by Mikori Games on Discord.
Could be related to half-precision calculations that are ignored by Unity on PC. Needs testing on Android/iOS or any other platform where float precision matters

**Comment by diogovtx** [comment]
We don't seem to have any half precision calculations in our Impostors code. Could be caused by using a half-precision Depth buffer on the device settings.
