### ISSUE TITLE
URP 14x shadowMask Bug

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyImpostors-Feedback#25]
first found in 2022.3.5 URP 14.0.8
verified

Runtime OctahedronImpostorURP
Render path Deferred.
when parent object is baked with shadowmask lighting impostors in last shadow cascade produces artifacts

![Impostor](https://github.com/AmplifyCreations/AmplifyImpostors-Feedback/assets/7001068/5b7242ac-a972-4a65-8b79-df78e68185ff)

**Comment by diogovtx** [comment]
Fixed. To be released with v0.9.9.1

FIX NOTE:
The fix involves completely disabling Shadow Mask on impostors. Unfortunately we can't support lightmaps/shadowmasks on impostors in a robust, reliable way. We can only support dynamic lighting at this time.
