### ISSUE TITLE
Amplify Imposters not adding asset models to the references area - does not work in 2020 or 2021

### ISSUE THREAD

**Issue by lunarexgames** [AmplifyCreations/AmplifyImpostors-Feedback#3]
It looks like part of the issue that I have with Amplify Imposters is that it's not adding the asset to the references area. 

After some testing it looks like the "references" are not adding any models in 2020, or 2021. 2019 seems to work but still have issues on quality in 2019.

**Comment by Dawie3565** [comment]
**this item is now tracking in**
https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/177
