### ISSUE TITLE
Refactor ASE templates and node

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyImpostors-Feedback#33]
Rename vertex to positionOS
Rename ase_normal to normalOS
Rename ase_tangent to tangentOS
Rename clipPos to positionCS
Rename worldPos to positionWS

**Comment by diogovtx** [comment]
Done in v0.9.9.4

**Comment by BOXOPHOBIC** [comment]
Quick note, positionOS/normalOS cannot be used in BIRP because the pos and normal have hard coded names in unity internals.

**Comment by BOXOPHOBIC** [comment]
Issues with Depth Primming (I think when using instanced indirect rendering, I cannot confirm yet) and VR support have been reported when using the AI templates.

**Comment by diogovtx** [comment]
> Issues with Depth Primming (I think when using instanced indirect rendering, I cannot confirm yet) and VR support have been reported when using the AI templates.

Fixed some depth priming issues in SRP but we'll keep an eye for others.
