### ISSUE TITLE
Update templates per latest ASE version

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyImpostors-Feedback#36]
Impostors **v0.9.9.3**
testing in URP 12x (demo Custom Baking) 
runtime shaders using AmplifyImpostorsTemplateURP do not render correctly. 

Templates seam to not be updated per the latest ASE changes from ASE version v1.9.2.2 and higher 

reference:
Renamed vertex to positionOS
Renamed ase_normal to normalOS
Renamed ase_tangent to tangentOS
Renamed clipPos to positionCS
Renamed worldPos to positions

to reproduce download Impostors and see demo scene for Custom Baking

**Comment by diogovtx** [comment]
Closing as not planned due to being a combination of existing tasks:
https://github.com/AmplifyCreations/AmplifyImpostors-Feedback/issues/33
https://github.com/AmplifyCreations/AmplifyImpostors-Feedback/issues/39
https://github.com/AmplifyCreations/AmplifyImpostors-Feedback/issues/37
