### ISSUE TITLE
LOD crossfade not working in URP

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyImpostors-Feedback#4]
Hello,

Using Unity 2020.3.30f1 and URP 10.8.1,

I am trying to use the crossfade LOD effect with the impostors but it doesn't work. The impostor appears immediately without the crossfade effect.
I managed to progress somehow but I'm still struggling to get the wanted result.

For the impostor, I'm using a copy of the shader OctahedronImpostorURP (found in AmplifyImpostors\Plugins\EditorResources\Shaders\Runtime\OctahedronImpostor.shader) and added this line at the beginning of the frac function :
- LODDitheringTransition(IN.clipPos.xy, unity_LODFade.x);
By doing so, the transition works. But the final state is that the impostor will always be invisible.
On the gif, the default model is on the left and the impostor is on the right.

Thank you kindly.
Pampou

![image](https://user-images.githubusercontent.com/7001068/199121301-0cb0604d-4ec0-4fe7-ac7a-e8e47fccede3.png)

**Comment by Pampou** [comment]
I finally managed to get things right.
Just add + 1 to the second parameter of the function LODDitheringTransition.

So the final fix is adding this line :
LODDitheringTransition(IN.clipPos.xy, unity_LODFade.x + 1);

at the beginning of the frac function of the OctahedronImpostorURP.shader.

You might add this line for the shader SphericalImpostorURP as well.

**Comment by diogovtx** [comment]
Thank you for sorting this out and sharing the fix. Highly appreciated.

**Comment by Dawie3565** [comment]
**this item is now tracking in**
https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/176
