### ISSUE TITLE
URP Lit 14x detail map is resulting in dark impostors 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyImpostors-Feedback#55]
first found in URP 14x 
when URP Lit shader has detail map (with no Normal map used) the results from bake are much darker

--- Open example demo Barrels & Boulders
--- see prefab "Barrel URP"
---- observe bake is much darker than model when detail map is used when detail map has no normal map applied

**Comment by diogovtx** [comment]
This appears to be a Unity bug. If I replace the empty Detail Normal Map slot with a flat normal map, it works fine.

I'll see if I can work around it.

**Comment by diogovtx** [comment]
Successfully added a workaround. Done.
