### ISSUE TITLE
custom lighting opaque behaves like a transparent and doesn't write to depth (in BIRP and URP on unity 2020.3.48)

### ISSUE THREAD

**Issue by laurentopia** [AmplifyCreations/AmplifyImpostors-Feedback#68]
http://paste.amplify.pt/view/raw/bdbbc408
the shadow appears in front of custom lit ASE opaques
https://github.com/user-attachments/assets/32881678-a7bb-49bc-9b37-7dbe9d390e57

but gets occluded properly behind a standard opaque shader
https://github.com/user-attachments/assets/8ee6eb54-3059-48f9-95f1-8799a9f3cfcf

**Comment by Dawie3565** [comment]
close and move to ASE Git
