### ISSUE TITLE
Fix potential impostor depth precision issues on Quest

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyImpostors-Feedback#7]
Reported by Mikori Games on Discord.

Could be related to half-precision calculations that are ignored by Unity on PC. Needs testing on Android/iOS or any other platform where float precision matters.

**Comment by Dawie3565** [comment]
**this item is now tracking in**
https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/174
