### ISSUE TITLE
BUG BIRP Template - Shaders not working with Instancing

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyImpostors-Feedback#9]
Some passes skip instancing variants, not working with instanced indirect renderers.

**Comment by BOXOPHOBIC** [comment]
Fixed in my birp template

**Comment by Dawie3565** [comment]
**this item is now tracking in**
https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/173
